name: Python CI

on:
  push:
    branches:
      - master
jobs:
        deploy:
          runs-on: ubuntu-latest
          steps:
            - name: Checkout repository
              uses: actions/checkout@v2
            
            - name: Copy master-fe directory
              run: cp -r master-fe/* .
            
            - name: Upload artifacts
              uses: actions/upload-artifact@v2
              with:
                name: master-fe
                path: .
      
